version: '3.4'
services:
    openfire:
      image: matheusilvex/openfire-4.2.2_mysql
      container_name: openfire
      ports:
        - 0.0.0.0:9090
        - 0.0.0.0:9091
        - 0.0.0.0:5222 
        - 0.0.0.0:5269
        - 0.0.0.0:5223
        - 0.0.0.0:7443
        - 0.0.0.0:7777
        - 0.0.0.0:7070
        - 0.0.0.0:5229
        - 0.0.0.0:5275
        - 5000:6000/tcp
        - 5000:6000/udp 
      depends_on:
        - db
    db:
      image: mysql:5.6
      container_name: database
      environment:
        - MYSQL_ROOT_PASSWORD=h0sp1t4l  
        - MYSQL_DATABASE=openfire
        - MYSQL_USER=openfire
        - MYSQL_PASSWORD=h0sp1t4l