version: '3.4'
services:
    openfire:
      image: matheusilvex/openfire-4.2.2_mysql
      container_name: openfire
      ports:
        - 9090:9090
        - 9091:9091
        - 5222:5222 
        - 5269:5269
        - 5223:5223
        - 7443:7443
        - 7777:7777
        - 7070:7070
        - 5229:5229
        - 5275:5275
        - 5000:6000/tcp
        - 5000:6000/udp 
      tty: true
      depends_on:
        - db
      links:
        - db:dados
    db:
      image: mysql:5.6
      container_name: database
      environment:
        - MYSQL_ROOT_PASSWORD=h0sp1t4l  
        - MYSQL_DATABASE=openfire
        - MYSQL_USER=openfire
        - MYSQL_PASSWORD=h0sp1t4l